apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  creationTimestamp: null
  generateName: hello-run-
spec:
  resources: {}
  serviceAccountName: ""
  taskRef:
    name: hello
status:
  podName: ""
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: hello
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        echo "Hello World!"
        for i in {1..10}
        do
          echo "...looking around"
          sleep 1s
        done
        echo "Goodbye World!"
