apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  params:
  - name: message
    description: message to append to Hello/Goodbye
  steps:
    - name: hello
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        echo "Hello $(params.message)!"
        for i in {1..20}
        do
          echo "...looking around"
          sleep 1s
        done
        echo "Goodbye $(params.message)!"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
  - name: message
    type: string
    description: Message to print.
  tasks:
  - name: hello
    taskRef:
      name: hello
    params:
    - name: message
      description: message to append to Hello/Goodbye
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-main
spec:
  pipelineRef:
    name: pipeline
  params:
  - name: message 
    value: {{message}}