# apiVersion: tekton.dev/v1beta1
# kind: TaskRun
# metadata:
#   creationTimestamp: null
#   generateName: pipeline-main
# spec:
#   resources: {}
#   serviceAccountName: ""
#   taskRef:
#     name: hello
# status:
#   podName: ""
# ---

apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipeline-main
spec:
  serviceAccountName: dockerhub-builder
  pipelineRef:
    name: pipeline
  # workspaces:
  # - name: shared-data
  #   volumeClaimTemplate:
  #     spec:
  #       accessModes:
  #       - ReadWriteOnce
  #       resources:
  #         requests:
  #           storage: 1Gi
  # - name: dockerconfig
  #   secret:
  #     secretName: dockerhub-docker-config
  #     items:
  #         - key: .dockerconfigjson
  #           path: config.json
  params:
  - name: repo-url
    value: https://github.com/swashbuck1r/simple-container-app
  - name: branch-name
    value: main
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  tasks:
    - name: say-hello
      taskRef:
        name: hello
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: hello
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        echo "Hello World!"
        for i in {1..10}
        do
          echo "...looking around"
          sleep 1s
        done
        echo "Goodbye World!"
